package org.ankarton.network;

public class OpCode {
	
	public enum Send {
		RECONNECTION_TICKET(2),
		RECONNECTION_TICKET_REQUEST_RESULT(4),
		INVALID_VERSION(8),
		AUTHENTICATION_RESULT(1024),
		WORLD_SERVER_UNAVAILABLE(1026),

		OPPONENT_FOUND(2300),
		OPPONENT_SEARCH_ERROR(2302),
		OPPONENT_SEARCH_IN_PROGRESS(2304),
		OPPONENT_SEARCH_CANCEL_RESULT(2306),

		COACH_CREATION_REQUEST(2048),
		COACH_CREATION_RESULT(2050),
		COACH_INFORMATION(2052),
		
		PLAYER_STATISTICS_REPORT(2400),
		
		VICINITY_MESSAGE(3152),
		PRIVATE_MESSAGE(3154),
		
		USER_NOT_FOUND(3204),
		MEMBER_NOT_FOUND(3208),
		
		ACTOR_SPAWN(4096),
		ACTOR_DESPAWN(4098),
		ACTOR_APPEAR(4102),
		ACTOR_DISAPPEAR(4104),
		ACTOR_REPOSITION(4106),

		READY_FOR_FIGHT(4306),
		
		ACTOR_MOVEMENT(4500),
		ACTOR_TELEPORT(4510),
		ENTER_WORLD_INSTANCE(4600),

		COACH_INVENTORY_UPDATE_MESSAGE(5200),
		COACH_EQUIPMENT_UPDATE_MESSAGE(5202),

        FIGHTER_CREATE_RESULT(6000),
        FIGHTER_DELETION_RESULT(6002),
        FIGHTER_INFORMATION_LIST(6006),
        FIGHTER_UPDATED_INFORMATION_INVENTORY(6010),

        TEAM_PRESET_SAVE(6020),
		TEAM_PRESET_DELETION(6022),
		TEAM_PRESET_LIST(6030),

		CREATE_FIGHT(8000),
		START_PRESENTATION(8010),
		END_PRESENTATION(8018),
		START_PLACEMENT(8020),
		END_PLACEMENT(8028),
		START_OBSERVATION(8030),
		END_OBSERVATION(8038),

		QUEUE_NOTIFICATION(8192),
		CONSOLE_ADMIN_COMMAND(8193),
		CONSOLE_ADMIN_COMMAND_RESULT(8194),
		DEFAULT_RESULT(8195);

		public final int value;

		Send(int value) {
			this.value = value;
		}

		public static Send get(int type) {
			for(Send code : Send.values())
				if(code.value == type)
					return code;
			return null;
		}
	}
	
	public enum Recv {
		DISCONNECT(1),
		VERSION(7), 
		AUTHENTICATION(1025), 
		COACH_CREATION(2049),

		OPPONENT_SEARCH_REQUEST(2301),
		OPPONENT_SEARCH_CANCEL(2303),

		VICINITY_MESSAGE(3153),
		PRIVATE_MESSAGE(3155),

		SET_READY_FOR_FIGHT(4303),

		ACTOR_MOVEMENT_REQUEST(4501),

		COACH_EQUIPMENT_UPDATE_REQUEST(5201),

		FIGHTER_CREATE_REQUEST(6001),
		FIGHTER_DELETE_REQUEST(6003),
		FIGHTER_INFORMATION_LIST_REQUEST(6005),
		FIGHTER_UPDATE_INVENTORY_REQUEST(6011),
		TEAM_PRESET_SAVE_REQUEST(6021),
		TEAM_PRESET_DELETE_REQUEST(6023),
		TEAM_PRESET_LIST_REQUEST(6031),

		SPELL_CAST_REQUEST(8109);

		public final int value;

		Recv(int value) {
			this.value = value;
		}

		public static Recv get(int type) {
			for(Recv code : Recv.values())
				if(code.value == type)
					return code;
			return null;
		}
	}
}